using System;
using Godot;
using GUnit.Library.Base;

namespace GUnit.Demo.Gunit;

//Autogenerated: Do not change the path of this file. It can lead to strange behaviour when running tests.
public partial class GodotTestRunner : SceneTree
{
    public override async void _Initialize()
    {
        var engine = new TestEngine(this);
        await engine.RunAll();
        Quit();
    }
}
    