using System;
using System.Threading.Tasks;
using Godot;
using GUnit.Library.Base;

namespace GUnit.Demo.Gunit;

//Autogenerated: Do not change the path of this file. It can lead to strange behaviour when running tests.
public partial class GodotTestRunner : SceneTree
{
    public override void _Initialize()
    {
        _ = RunTests();
    }

    private async Task RunTests()
    {
        var engine = new TestEngine(this);
        var testsSucceeded = await engine.RunAll();

        await ToSignal(this, SceneTree.SignalName.ProcessFrame); 
        await ToSignal(this, SceneTree.SignalName.PhysicsFrame);

        CallDeferred(nameof(Quit));

        System.Environment.Exit(testsSucceeded ? 0 : 1);
    }
}
    