namespace Gunit.CLI.Commands;

public class InitCommand : ICommand
{
    public void Execute()
    {
        var projectRoot = Directory.GetCurrentDirectory();
        var targetDir = Path.Combine(projectRoot, "GUnit");
        Directory.CreateDirectory(targetDir);

        var filePath = Path.Combine(targetDir, "GodotTestRunner.cs");

        if (File.Exists(filePath))
        {
            Console.WriteLine("⚠️ TestRunner already exists.");
            return;
        }

        File.WriteAllText(filePath, GetTemplate());
        Console.WriteLine("✅ GodotTestRunner created.");
    }

    private string GetTemplate() => @"using System;
using Godot;
using GUnit.Library.Base;

//Autogenerated: Do not change the path of this file. It can lead to strange behaviour when running tests.
public partial class GodotTestRunner : SceneTree
{
    public override async void _Initialize()
    {
        var engine = new TestEngine(this);
        var result = await engine.RunAll();

        if (result.Failed > 0)
        {
            foreach(var error in result.Errors)
            {
                Console.WriteLine(error.Message);
                Console.WriteLine(error.StackTrace);
            }

            throw new Exception(result.Failed + "" tests did not pass"");
        }

        Quit();
    }
}
    ";
}