namespace Gunit.CLI.Commands;

public class InitCommand : ICommand
{
    public async Task Execute()
    {
        var projectRoot = Directory.GetCurrentDirectory();
        var targetDir = Path.Combine(projectRoot, "GUnit");
        Directory.CreateDirectory(targetDir);

        var filePath = Path.Combine(targetDir, "GodotTestRunner.cs");

        if (File.Exists(filePath))
        {
            Console.WriteLine("⚠️ TestRunner already exists.");
            return;
        }

        await File.WriteAllTextAsync(filePath, GetTemplate());
        Console.WriteLine("✅ GodotTestRunner created.");
    }

    private string GetTemplate() => @"using System;
using Godot;
using GUnit.Library.Base;
using System.Threading.Tasks;

//Autogenerated: Do not change the path of this file. It can lead to strange behaviour when running tests.
public partial class GodotTestRunner : SceneTree
{
    public override async void _Initialize()
    {
        var engine = new TestEngine(this);
        await engine.RunAll();
        await Task.Delay(100);
        Quit();
    }
}
    ";
}