using GUnit.Shared.Models;

namespace Gunit.CLI.Commands;

public class InitCommand : ICommand
{
    public async Task Execute(List<CommandParameter> commandParameters)
    {
        var projectRoot = Directory.GetCurrentDirectory();
        var targetDir = Path.Combine(projectRoot, "GUnit");
        Directory.CreateDirectory(targetDir);

        var filePath = Path.Combine(targetDir, "GodotTestRunner.cs");

        if (File.Exists(filePath))
        {
            Console.WriteLine("⚠️ TestRunner already exists.");
            return;
        }

        await File.WriteAllTextAsync(filePath, GetTemplate());
        Console.WriteLine("✅ GodotTestRunner created.");
    }

    private string GetTemplate() => @"using System;
using Godot;
using GUnit.Library.Base;
using System.Threading.Tasks;

//Autogenerated: Do not change the path of this file. It can lead to strange behaviour when running tests.
public partial class GodotTestRunner : SceneTree
{
    public override void _Initialize()
    {
        _ = RunTests();
    }

    private async Task RunTests()
    {
        var engine = new TestEngine(this);
        var testsSucceeded = await engine.RunAll();

        await ToSignal(this, SceneTree.SignalName.ProcessFrame); 
        await ToSignal(this, SceneTree.SignalName.PhysicsFrame);

        Quit(testsSucceeded ? 0 : 1);
    }
}
    ";
}