<Project Sdk="Godot.NET.Sdk/4.6.2">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <nullable>enable</nullable>
  </PropertyGroup>

<PropertyGroup>
  <EnableGodotSourceGenerators>false</EnableGodotSourceGenerators>
  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>

  <Description>Godot testing framework</Description>
  <PackageTags>godot testing unit-test</PackageTags>

  <PackageId>GUnit</PackageId>
  <Version>0.3.1</Version>
  <Authors>Samuel Matarese</Authors>

  <RepositoryUrl>https://github.com/samuelmatarese/GUnit</RepositoryUrl>
  <PackageProjectUrl>https://github.com/samuelmatarese/GUnit</PackageProjectUrl>

  <PackageLicenseExpression>MIT</PackageLicenseExpression>

  <PublishRepositoryUrl>true</PublishRepositoryUrl>
</PropertyGroup>

</Project>