<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <nullable>enable</nullable>
  </PropertyGroup>

<PropertyGroup>
  <EnableGodotSourceGenerators>false</EnableGodotSourceGenerators>
  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>

  <Description>Godot testing framework</Description>
  <PackageTags>godot testing unit-test</PackageTags>

  <PackageReadmeFile>README.md</PackageReadmeFile>

  <PackageId>GUnit</PackageId>
  <Version>0.4.3</Version>
  <Authors>Samuel Matarese</Authors>

  <RepositoryUrl>https://github.com/samuelmatarese/GUnit</RepositoryUrl>
  <PackageProjectUrl>https://github.com/samuelmatarese/GUnit</PackageProjectUrl>

  <PackageLicenseExpression>MIT</PackageLicenseExpression>

  <PublishRepositoryUrl>true</PublishRepositoryUrl>
  <IncludeReferencedProjects>true</IncludeReferencedProjects>
</PropertyGroup>

<ItemGroup>
  <Compile Include="..\GUnit.Shared\**\*.cs" />
</ItemGroup>

<ItemGroup>
  <PackageReference Include="GodotSharp" Version="4.6.2" />
</ItemGroup>

<ItemGroup>
  <None Include="../README.md" Pack="true" PackagePath="\"/>
</ItemGroup>

<Target Name="InjectPackageReleaseNotesFromFile" BeforeTargets="GenerateNuspec" Condition="Exists('CHANGELOG.md')">
	<PropertyGroup>
		<PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/CHANGELOG.md"))</PackageReleaseNotes>
	</PropertyGroup>
</Target>
</Project>